### ISSUE TITLE
Add a illustrative map

### ISSUE THREAD

**Issue by Abusayid693** [Abusayid693/Hackathon-website-template#14]
Something like this but it should not be a static image rather show info when user hovers over it

![Screenshot 2021-08-11 at 2 30 37 AM](https://user-images.githubusercontent.com/35341198/128935141-a641cdda-2c69-478f-b10f-ce169816f9e6.png)

Resources : https://codesandbox.io/s/iz9vb

**Comment by ZohebMOPO** [comment]
Wait @Abusayid693 I have done something like this before

**Comment by ZohebMOPO** [comment]
Btw my first hackathon was a project of this thing

**Comment by ZohebMOPO** [comment]
What should we show in the map?

**Comment by Abusayid693** [comment]
@ZohebMOPO O yeah thats nice , map should be interactive one just as an example like GitHub home page map that shows where PR is made when someone clicks just like this our map should contain few highlighted points and show how many hackers are from which region , don't need to show country just region (Asia, North America etc) and it **should not be a actual map basically a illustrative one**

**Comment by ZohebMOPO** [comment]
@Abusayid693 PR #24
