### ISSUE TITLE
Need to fix for screen size below 370px

### ISSUE THREAD

**Issue by Abusayid693** [Abusayid693/Hackathon-website-template#19]
https://github.com/Limbo-Hacks/Hackathon-website-template/blob/e241b5ae1b33405a2edf6370656e2d5a9ca7ccb8/src/components/navbar/styles.scss#L78

**Comment by adityamangal1** [comment]
@Abusayid693 You can close this issue

**Comment by Abusayid693** [comment]
Issue fixed
