### ISSUE TITLE
schedule is not connected to main page

### ISSUE THREAD

**Issue by naqeeb2710** [Abusayid693/Hackathon-website-template#23]

**Comment by ZohebMOPO** [comment]
We have the schedule code but we didn't add it to the main page as we have not decided the schedule fully yet :)

**Comment by naqeeb2710** [comment]
can you guide me on how can I add it to the main page since I'm using your template for the upcoming hackathon in my college. also, the navbar keys and faqs aren't properly formatted for mobile view.

**Comment by adityamangal1** [comment]
Hey @naqeeb2710 , will fix that mobile view issue thanks for letting us know

**Comment by ZohebMOPO** [comment]
@naqeeb2710 check this https://github.com/Limbo-Hacks/Hackathon-website-template/pull/6 on where to add

**Comment by Abusayid693** [comment]
@naqeeb2710 Schedule is now connected to main application, closing this issue
