### ISSUE TITLE
Schedule section

### ISSUE THREAD

**Issue by Abusayid693** [Abusayid693/Hackathon-website-template#5]
Add a schedule section right below faqs

**Comment by ZohebMOPO** [comment]
We need to discuss that in a call, in what time what will start and what will end at what time

**Comment by Abusayid693** [comment]
Will do b4 event , I was talking about schedule section templates

**Comment by ZohebMOPO** [comment]
Close this issue @Abusayid693

**Comment by Abusayid693** [comment]
Done
